routes/web.php
<?php

use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\CritereEvaluationController;
use App\Http\Controllers\CriterePerformanceController;
use App\Http\Controllers\ElementCompetenceController;
use App\Http\Controllers\PlanCadreController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProgrammeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::resource('competence', CompetenceController::class, [
    'parameters' => ['Competence' => 'competence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereevaluation', CritereEvaluationController::class, [
    'parameters' => ['CritereEvaluation' => 'critereevaluation']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereperformance', CriterePerformanceController::class, [
    'parameters' => ['CriterePerformance' => 'critereperformance']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('elementcompetence', ElementCompetenceController::class, [
    'parameters' => ['ElementCompetence' => 'elementcompetence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('plancadre', PlanCadreController::class, [
    'parameters' => ['PlanCadre' => 'plancadre']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('profil', ProfileController::class);

Route::resource('programme', ProgrammeController::class, [
    'parameters' => ['Programme' => 'programme']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);


Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Competence.php
<?php

namespace App\Models;

use Brick\Math\BigInteger;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Competence extends Model
{
    use HasFactory;

    protected $table = 'competences';

    public function plancadres(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(PlanCadre::class);
    }

    public function elementcompetence(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Competence::class, 'competences_id', 'id');
    }

    protected $fillable = [
        'code',
        'titre',
        'enonce',
        'annee_devis',
        'pages_devis',
        'contexte',
        'contexte_local'
    ];
}

app/Http/Controllers/CompetenceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Competence;
use App\Models\ElementCompetence;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use JavaScript;

class CompetenceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('competence.index', ['competences' => Competence::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        JavaScript::put([
            'elementcompetences' => ElementCompetence::all()
        ]);

        return view ('competence.nouveau');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validateCompetence($request);
        $competence = Competence::create([
            'code' => $request->code,
            'titre' => $request->titre,
            'ennonce' => $request->ennonce,
            'annee_devis' => $request->annee_devis,
            'contexte' => $request->contexte,
            'contexte_local' => $request->contexte_local
        ]);

        // @TODO multiple element competence (parler a la prof)
        if(isset($request->elementcompetence)){
            $competence->elementcompetence()->attach(Competence::find($request->elementcompetence));
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Competence $competence)
    {
        return view ('competence.show', ['Competence' => $competence]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        return view('competence.modifier', ['competence' => Competence::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Competence $competence)
    {
        $this->validateCompetence($request);

        // @TODO Il manque des champs dans le form
        $comp = Competence::where('id', $competence->id)->update([
            'code' => $request->code,
            'titre' => $request->titre,
            'ennonce' => $request->ennonce,
            'annee_devis' => $request->annee_devis,
            'contexte' => $request->contexte,
            'contexte_local' => $request->contexte_local
        ]);

        // @TODO update multiple element competence (parler a la prof)
        if(isset($request->elementcompetence)){
            $comp->elementcompetence()->attach(Competence::find($request->elementcompetence));
        }
        $comp->save();

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Gate::authorize('isAdmin');
        $competence = Competence::where('id' , $id)->delete();
    }

    private function validateCompetence(Request $request): array
    {
        return $request->validate([
            'code' => 'required|string|min:6|max:12',
            'titre' => 'required|string|max:255',
            'annee_devis' => 'integer',
            'ennonce' => 'required|string|max:255',
            'page_devis' =>'nullable|string|max:255',
            'contexte' =>'string|nullable',
            'contexte_local' =>'nullable|string'
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/formulaireCompetence.php
<?php

namespace App\View\Components;

use App\Models\Competence;
use App\Models\ElementCompetence;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\View\Component;

class formulaireCompetence extends Component
{
    public Collection $element;
    public string $textBoutton;
    /**
     * Create a new component instance.
     */
    public function __construct(public string $texteBoutton = "Enregistrer", public ?Competence $competence = null)
    {
        $this->textBoutton = $this->texteBoutton;
        $this->element = ElementCompetence::all();
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('competence.formulaire');
    }
}

resources/views/Competence/formulaire.blade.php
{{-- @TODO Formulaire pour ajouter et modifier
Code inspirer de la prof Pour le formulaire --}}

{{-- Code --}}
<div class="my-3">
    <label for="code" class="form-label">No</label>
    <input required name="code" id="code" type="text" placeholder="420-4P6-HU" class="form-control">
    @error('code')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Titre --}}
<div class="my-3">
    <label for="titre" class="form-label">Titre</label>
    <input required name="titre" id="titre" class="form-control">
    @error('titre')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Ennonce --}}
<div class="my-3">
    <label for="ennonce" class="form-label">Ennonce</label>
    <input required name="ennonce" id="ennonce" class="form-control">
    @error('ennonce')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Context --}}
<div class="my-3">
    <label for="context" class="form-label">Context</label>
    <input required name="context" id="context" class="form-control">
    @error('context')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Context_local --}}
<div class="my-3">
    <label for="context_local" class="form-label">Context local</label>
    <input required name="context_local" id="context_local" class="form-control">
    @error('context_local')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Annee_devis --}}
<div class="my-3">
    <label for="annee_devis" class="form-label">Annee de devis?</label>
    <input required name="annee_devis" id="context" class="form-control" type="number">
    @error('annee_devis')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Page_devis --}}
<div class="my-3">
    <label for="pages_deivs" class="form-label">Page de devis?</label>
    <input required name="pages_devis" id="pages_devis" class="form-control">
    @error('pages_devis')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Element Competence --}}
<div class="my-3">
    <div class="flex">
        <label for="elementcompetence_plus" class="form-label">Element de Competence(s)</label>
        <button id="elementcompetence_plus" class="btn btn-secondary rounded-circle btn-sm" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
        </button>
        <a href="{{route('elementcompetence.create')}}" type="button" class="btn btn-secondary btn-sm">Nouvelle</a>
    </div>
    <?php  // donner une id unique a toutes les composantes pour pas creer de trouble au submit
    $compte = 1; ?>
    <div id="elementcompetence_select">
        @foreach($competence?->elementcompetence as $comp)
            <select id="elementcompetence{{$compte}}" name="elementcompetence" class="form-select">
                <option value="">---</option>
                @foreach($elementcompetences as $element)
                    @if($element->id == $comp->id)
                        <option value="{{$element->id}}" selected>{{$element->titre}} - {{$element->code}}</option>
                    @else
                        <option value="{{$element->id}}">{{$element->titre}} - {{$element->code}}</option>
                    @endif
                @endforeach
            </select>
            <?php $compte += 1 ?>
        @endforeach
    </div>

    @error('competence')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>


<button type="submit" class="btn btn-primary">{{$textBoutton}}</button>

resources/views/Competence/index.blade.php
<x-app-layout>
    <div class="flex">
        <div class="">
            <div class="">
                <div class="">
                    <h1 class="">Ceci est la liste de competence</h1>
                </div>
                @auth
                    <div class="">
                        <a href="{{route('competence.create')}}" class="btn-primary">Ajouter</a>
                    </div>
                @endauth
            </div>
            <br>
            <table class="table table-striped">
                <tbody>
                @foreach($competences as $competence)
                    <tr>
                        <th scope="row" >
                            <p>{{$competence->code}} {{$competence->titre}}</p>
                        </th>
                        <td>
                            <a href="{{route('competence.show', $competence->id)}}">Voir</a>
                        </td>
                        <td>
                            <a href="{{route('competence.edit', $competence->id)}}">Modifier</a>
                        </td>
                        <td>
                            <a href="{{route('competence.destroy', $competence->id)}}">Effacer</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>

resources/views/Competence/modifier.blade.php
<x-app-layout>
    <h1>Modifier {{$competence->titre}}</h1>
    <form method="post" action="{{route('competence.update', ['competence'=>$competence->id])}}">
        @csrf
        @method('PUT')
        <x-formulaire-competence texte-bouton="Modifier" :competence="$competence"></x-formulaire-competence>
    </form>
</x-app-layout>

resources/views/Competence/nouveau.blade.php
<x-app-layout>
    <h1>Nouvelle competence</h1>
    <form method="post" action="{{route('competence.store')}}">
        @csrf
        <x-formulaire-competence texte-bouton="Nouveau"></x-formulaire-competence>
    </form>
</x-app-layout>

resources/views/Competence/show.blade.php
<?php