routes/web.php
<?php

use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\CritereEvaluationController;
use App\Http\Controllers\CriterePerformanceController;
use App\Http\Controllers\ElementCompetenceController;
use App\Http\Controllers\PlanCadreController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProgrammeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::resource('competence', CompetenceController::class, [
    'parameters' => ['Competence' => 'competence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereevaluation', CritereEvaluationController::class, [
    'parameters' => ['CritereEvaluation' => 'critereevaluation']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereperformance', CriterePerformanceController::class, [
    'parameters' => ['CriterePerformance' => 'critereperformance']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('elementcompetence', ElementCompetenceController::class, [
    'parameters' => ['ElementCompetence' => 'elementcompetence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('plancadre', PlanCadreController::class, [
    'parameters' => ['PlanCadre' => 'plancadre']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('profil', ProfileController::class);

Route::resource('programme', ProgrammeController::class, [
    'parameters' => ['Programme' => 'programme']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);


Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/PlanCadre.php
<?php

namespace App\Models;

use Brick\Math\BigInteger;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Date;

class PlanCadre extends Model
{
    use HasFactory;

    protected $table = 'plan_cadres';

    public function programme(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Programme::class, 'plancadre_id');
    }

    public function critereevaluation(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(CritereEvaluation::class, 'plancadre_id');
    }

    public function competence(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Competence::class, 'plancadres_competences', 'plancadres_id', 'competences_id')->withPivot('complete');
    }

    public function prealable(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(PlanCadre::class,'plancadres_prealable', 'plan_cadre_id', 'prealable_id')->withPivot(['absolu']);
    }

    public function corequi(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(PlanCadre::class,'plancadres_corequi', 'plan_cadre_id', 'corequi_id');
    }

    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function joinUser($user_id){
        $this->user()->associate($user_id);
        $this->save();
    }

    protected $fillable = [
        'code',
        'titre',
        'ponderation',
        'unite',
        'attitudes',
        'intentions_educatives',
        'intentions_pedagogiques',
        'desc_cours',
        'changement',
        'approbation_depart',
        'approbation_comite',
        'ponderation_final'
    ];
}

app/Http/Controllers/PlanCadreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Competence;
use App\Models\CriterePerformance;
use App\Models\ElementCompetence;
use App\Models\PlanCadre;
use App\Models\Programme;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use JavaScript;

class PlanCadreController extends Controller
{
    public function __construct(){
        $this->middleware("auth");
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\View|\Illuminate\Contracts\Foundation\Application
    {
        // seul les admin peuvent tout voir
        if(Auth::user()->isAdmin == 1){
            $plancadre = PlanCadre::all();
        }
        else{
            $plancadre = PlanCadre::where('user_id', Auth::user()->id)->get();
        }

        return view('plancadre.index', ['plancadres' => $plancadre]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\View|\Illuminate\Contracts\Foundation\Application
    {
        JavaScript::put([
            'plancadres' => PlanCadre::all(),
            'competences' => Competence::all()
        ]);

        return view('plancadre.nouveau');
    }


    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request): \Illuminate\Http\RedirectResponse
    {
        $this->validatePlanCadre($request);
        $plancadre = PlanCadre::create([
            'code' => $request->code,
            'titre' => $request->titre,
            'ponderation' => $request->ponderation,
            'unite' => $request->unite,
            'intentions_educatives' => $request->intentions_educatives,
            'attitudes' => $request->attitudes,
            'intentions_pedagogiques' => $request->intentions_pedagogiques,
            'desc_cours' => $request->desc_cours,
            'changement' => $request->changement,
            'approbation_depart' => $request->approbation_depart,
            'approbation_comite' => $request->approbation_comite,
            'ponderation_final' => $request->ponderation_final,
        ]);

        $plancadre->user()->associate(Auth::user()->id);

        if(isset($request->prealable)){
            foreach ($request->prealable as $i => $prea){
                $absolu = 0;
                if($request->absolu[$i] == 'on'){
                    $absolu = 1;
                }
                $plancadre->prealable()->attach(PlanCadre::find($prea), ['absolu'=>$absolu]);
            }
        }

        if(isset($request->cours)){
            foreach ($request->cours as $i => $cour){
                $plancadre->corequi()->attach(PlanCadre::find($cour));
            }
        }

        if(isset($request->competence)){
            foreach ($request->competence as $i => $comp){
                $complete = 0;
                if($request->complete[$i] == 'on'){
                    $complete = 1;
                }
                $plancadre->competence()->attach(Competence::find($comp), ['complete'=>$complete]);
            }
        }


        $plancadre->save();
        return redirect()->route('plancadre.index');
    }

    /**
     * Display the specified resource.
     */
    public function show($id): \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Contracts\View\View|\Illuminate\Contracts\Foundation\Application
    {
        return view ('plancadre.show', ['plancadre' => PlanCadre::find($id), 'elementcompetences' => ElementCompetence::all(), 'critereperformances' => CriterePerformance::all()]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id): \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
    {
        JavaScript::put([
            'plancadres' => PlanCadre::all(),
            'competences' => Competence::all()
        ]);

        return view('plancadre.modifier', ['plancadre' => PlanCadre::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, PlanCadre $plancadre): \Illuminate\Http\RedirectResponse
    {
        $this->validatePlanCadre($request);

        $plancadre = PlanCadre::where('id', $plancadre->id)->update([
            'code' => $request->code,
            'titre' => $request->titre,
            'ponderation' => $request->ponderation,
            'unite' => $request->unite,
            'intentions_educatives' => $request->intentions_educatives,
            'attitudes' => $request->attitudes,
            'intentions_pedagogiques' => $request->intentions_pedagogiques,
            'desc_cours' => $request->desc_cours,
            'changement' => $request->changement,
            'approbation_depart' => $request->approbation_depart,
            'approbation_comite' => $request->approbation_comite,
            'ponderation_final' => $request->ponderation_final
        ]);

        $plan = PlanCadre::find($plancadre);

        if(isset($request->prealable)){
            foreach ($request->prealable as $i => $prea){
                $absolu = 0;
                if(isset($request->absolu[$i])){
                    if($request->absolu[$i] == 'on'){
                        $absolu = 1;
                    }
                }
                $plan->prealable()->updateExistingPivot($prea, ['absolu' => $absolu]);
            }
        }
/*
        if(isset($request->cours)){
            foreach ($request->cours as $cour){
                $plan->corequi()->updateOrCreate([
                        'plan_cadre_id'=>$cour->plan_cadre_id,
                        'corequi_id'=>$cour->corequi_id
                    ]);
            }
        }*/

        if(isset($request->competence)){
            foreach ($request->competence as $i => $comp){
                $complete = 0;
                if(isset($request->complete[$i])){
                    if($request->complete[$i] == 'on'){
                        $complete = 1;
                    }
                }
                $plan->competence()->updateExistingPivot($comp, ['complete' => $complete]);
            }
        }

        $plan->save();
        return redirect()->route('plancadre.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Gate::authorize('isAdmin');
        $plancadre = PlanCadre::where('id' , $id)->delete();
        return redirect()->route('plancadre.index');
    }

    private function validatePlanCadre(Request $request): array
    {
        return $request->validate([
            'code' => 'required|string|min:6|max:12',
            'titre' => 'required|string|max:255',
            'ponderation' => 'required|string|max:255',
            'unite' => 'required|numeric|between:0.00,99.99',
            'attitudes' =>'nullable|string|max:255',
            'intentions_educatives' =>'nullable|string|max:255',
            'intentions_pedagogiques' =>'nullable|string',
            'desc_cours' =>'nullable|string',
            'changement' =>'nullable|date',
            'approbation_depart' =>'nullable|date',
            'approbation_comite' =>'nullable|date',
            'ponderation_final' =>'nullable|integer'
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/formulairePlancadre.php
<?php

namespace App\View\Components;

use App\Models\Competence;
use App\Models\PlanCadre;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\View\Component;

class formulairePlancadre extends Component
{
    public Collection $competence;
    public Collection $plancadres;
    public string $textBoutton;

    /**
     * Create a new component instance.
     */
    public function __construct(public string $texteBoutton = "Enregistrer", public ?PlanCadre $plancadre = null)
    {
        $this->textBoutton = $texteBoutton;
        $this->competence = Competence::all();
        $this->plancadres = PlanCadre::all();
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('plancadre.formulaire');
    }
}

resources/views/PlanCadre/index.blade.php
<x-app-layout>
    <div class="flex">
        <div class="">
            <div class="">
                <div class="">
                    <h1 class="">Ceci est la liste de plan cadre</h1>
                </div>
                @auth
                <div class="">
                    <a href="{{route('plancadre.create')}}" class="btn-primary">Ajouter</a>
                </div>
                @endauth
            </div>
            <br>
            <table class="table table-striped">
                <tbody>
                    @foreach($plancadres as $plancadre)
                        <tr>
                            <th scope="row" >
                                <p>{{$plancadre->code}} {{$plancadre->titre}} ({{$plancadre->ponderation}})</p>
                            </th>
                            <td>
                                <a href="{{route('plancadre.show', $plancadre->id)}}">Voir</a>
                            </td>
                            <td>
                                <a href="{{route('plancadre.edit', $plancadre->id)}}">Modifier</a>
                            </td>
                            @can('isAdmin')
                                <td>
                                    <a href="{{route('plancadre.destroy', $plancadre->id)}}">Effacer</a>
                                </td>
                            @endcan
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</x-app-layout>

resources/views/PlanCadre/modifier.blade.php
@include ('footer')
<x-app-layout>
    <h1>Modifier {{$plancadre->titre}}</h1>
    <form method="post" action="{{route('plancadre.update', ['plancadre' => $plancadre->id])}}">
        @csrf
        @method('PUT')
        <x-formulaire-plancadre texte-bouton="Modifier" :plancadre="$plancadre"></x-formulaire-plancadre>
    </form>
</x-app-layout>

resources/views/PlanCadre/nouveau.blade.php
@include ('footer')
<x-app-layout>
    <h1>Nouveau Plan Cadre</h1>
    <form method="POST" action="{{route('plancadre.store')}}">
        @csrf
        <x-formulaire-plancadre texte-bouton="Nouveau"></x-formulaire-plancadre>
    </form>
</x-app-layout>

resources/views/PlanCadre/show.blade.php
<x-app-layout>
    <div class="container">
        <div content="row">
            <div class="col">
                <h1>{{$plancadre->code}} {{$plancadre->titre}}</h1>
                <hr>
                {{-- @TODO Integrer l'image du cegep --}}
                <img src="">
                <h2>Plan-cadre</h2>
                <p>Titre du cours : {{$plancadre->titre}}</p>
                <p>Numero : {{$plancadre->code}}</p>
                <hr>
                {{-- Page principale --}}
                <p><b>ponderation : </b> {{$plancadre->ponderation}}</p>
                <p><b>Unité : </b>{{$plancadre->unite}}</p>
                {{-- @TODO Prealable --}}
                @foreach($plancadre->prealable as $pc)
                    @if($plancadre->absolu == 1)
                        <p><b>Prealable absolu : </b>{{$pc->code}} {{$pc->titre}} {{$pc->ponderation}}</p>
                    @elseif($plancadre->absolu == 0)
                        <p><b>Prealable : </b>{{$pc->code}} {{$pc->titre}} {{$pc->ponderation}}</p>
                    @endif
                @endforeach
                @foreach($plancadre->corequi as $pc)
                    <p><b>Cours co-requis : </b>{{$pc->code}} {{$pc->titre}} {{$pc->ponderation}}</p>
                @endforeach
                {{-- @TODO Competence (atteinte a voir?) --}}
                <table class="table">
                    <tr>
                        <th class="col">Compétence</th>
                        <th class="col">No</th>
                        <th class="col">Atteinte</th>
                    </tr>
                    @foreach($plancadre->competence as $competence)
                        <tr>
                            <td class="row">{{$competence->titre}}</td>
                            <td>{{$competence->code}}</td>
                            <td>{{$competence->ennonce}}</td>
                        </tr>
                    @endforeach
                </table>
                <p><b>Intentions éducatives, </b>Pages 7 et 8 du devis 2017</p>
                <p>Les intentions éducatives en formation spécifique s'appuient sur des valeurs
                    et préoccupations importantes et qui servent de guide aux interventions auprès de
                    l'étudiant ou de l'étudiante. Elles touchent généralement des dimensions significatives
                    du développement professionnel et personnel qui n'ont pas fait l'objet de formulations
                    explicites au niveau des buts de la formation ou des objectifs et standards. Elles
                    peuvent porter sur des attitudes importantes, des habitudes de travail, des habiletés
                    intellectuelles, etc.</p>
                <p>Pour le programme Technique de l'informatique, les intentions éducatives en formation
                    spécifique sont les suivantes :</p>
                <p>{{$plancadre->intentions_educatives}}</p>

                <p><b>Intentions pédagogiques</b></p>
                <p>{{$plancadre->intentions_pedagogiques}}</p>

                <p><b>Brève description du cours</b></p>
                <p>{{$plancadre->desc_cours}}</p>

                <table class="table table-bordered">
                    <tr>
                        <th class="col">OBJECTIF</th>
                        <th class="col">STANDARD</th>
                        <th class="col">PRÉCISIONS SUR LES CONTENUS</th>
                    </tr>
                    <tr>
                        <td><b>Énnoncé de la competence</b></td>
                        <td><b>Context de réalisation</b>, devis 2017, pp 67-68</td>
                        <td><b>Contexte de réalisation local</b></td>
                    </tr>
                    @foreach($plancadre->competence as $competence)
                        <tr>
                            <td>{{$competence->enonce}}</td>
                            <td>{{$competence->contexte}}</td>
                            <td>{{$competence->contexte_local}}</td>
                        </tr>
                    @endforeach
                    @foreach($plancadre->competence as $competence)
                    <tr>
                        <td colspan="3">
                                <p class="d-flex justify-content-center">Attitudes à enseigner et à évaluer pour la compétence {{$competence->code}}</p>
                                <p class="d-flex justify-content-center">autonomie, rigueur, collaboration et efficacite</p>
                                {{-- @TODO Mettre les element de competence --}}
                        </td>
                    </tr>
                    @endforeach
                </table>

                <table class="table table-bordered">

                    <tr>
                        <th class="col">Éléments de compétence</th>
                        <th class="col">Critère de performance</th>
                        <th class="col">Contenus locaux</th>
                    </tr>
                    <?php $compte1 = 1 ?>
                    @foreach($plancadre->competence as $competence)
                        @foreach($elementcompetences as $element)
                            @if($element->competence_id == $competence->id)
                                <tr>
                                    {{-- element de la competence --}}
                                    <td>{{$compte1}}. {{$element->texte}}</td>

                                    {{-- Critere performance --}}
                                    <?php $compte2 = 1 ?>
                                    <td>
                                        @foreach($critereperformances as $critere)
                                            @if($critere->elementcompetence_id == $element->id)
                                                {{$compte1}}.{{$compte2}} {{$critere->texte}}<br>
                                                <?php $compte2 += 1 ?>
                                            @endif
                                        @endforeach
                                    </td>

                                    {{-- contenu local --}}
                                    <td>{{$element->contenu_local}}</td>
                                </tr>
                                <?php $compte1 += 1 ?>
                            @endif
                        @endforeach
                    @endforeach

                </table>

                <div>
                    <p>Date d'adoption par le département 420 : {{$plancadre->approbation_depart}}</p>
                    <p>Date d'adoption par le Comité de programme : {{$plancadre->approbation_comite}}</p>
                    <p>Date du dépôt à la Direction des études : Techniques de l'informatique (420.B0.PS)</p>
                </div>

            </div>

            <div class="col d-flex align-items-center flex-column">
                <a class="btn btn-primary p-2" href="">Imprimer</a>
                <a class="btn btn-primary p-2" href="{{route('plancadre.edit', $plancadre->id)}}">Modifier</a>
                <button class="btn btn-primary p-2" href="" disabled>Plans de cours</button>
                <a class="btn btn-primary p-2" href="">Archiver</a>
                <a class="btn btn-primary p-2" href="{{route('plancadre.destroy', $plancadre->id)}}">Supprimer</a>
            </div>
        </div>
    </div>
</x-app-layout>