routes/web.php
<?php

use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\CritereEvaluationController;
use App\Http\Controllers\CriterePerformanceController;
use App\Http\Controllers\ElementCompetenceController;
use App\Http\Controllers\PlanCadreController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProgrammeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::resource('competence', CompetenceController::class, [
    'parameters' => ['Competence' => 'competence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereevaluation', CritereEvaluationController::class, [
    'parameters' => ['CritereEvaluation' => 'critereevaluation']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereperformance', CriterePerformanceController::class, [
    'parameters' => ['CriterePerformance' => 'critereperformance']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('elementcompetence', ElementCompetenceController::class, [
    'parameters' => ['ElementCompetence' => 'elementcompetence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('plancadre', PlanCadreController::class, [
    'parameters' => ['PlanCadre' => 'plancadre']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('profil', ProfileController::class);

Route::resource('programme', ProgrammeController::class, [
    'parameters' => ['Programme' => 'programme']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);


Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/CritereEvaluation.php
<?php

namespace App\Models;

use Brick\Math\BigInteger;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CritereEvaluation extends Model
{
    use HasFactory;

    public function plancadre(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(PlanCadre::class);
    }

    protected $fillable = [
        'enonce',
        'ponderation'
    ];
}

app/Http/Controllers/CritereEvaluationController.php
<?php

namespace App\Http\Controllers;

use App\Models\CritereEvaluation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class CritereEvaluationController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('CritereEvaluation.index', ['critereEvals' => CritereEvaluation::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('critereevaluation.nouveau');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(CritereEvaluation $critereEvaluation)
    {
        return view ('CritereEvaluation.show', ['CritereEvaluation' => $critereEvaluation]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(CritereEvaluation $critereEvaluation)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, CritereEvaluation $critereEvaluation)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(CritereEvaluation $critereEvaluation)
    {
        Gate::authorize('isAdmin');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/formulaireCritereEvaluation.php
<?php

namespace App\View\Components;

use App\Models\CritereEvaluation;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class formulaireCritereEvaluation extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(public string $texteBoutton = "Enregistrer", public ?CritereEvaluation $critereEvaluation = null)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('critereevaluation.formulaire');
    }
}

resources/views/CritereEvaluation/formulaire.blade.php
{{-- ennonce --}}
<div class="my-3">
    <label for="ennonce" class="form-label">No</label>
    <input required name="ennonce" id="ennonce" type="text" placeholder="420-4P6-HU" class="form-control">
    @error('ennonce')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Code --}}
<div class="my-3">
    <label for="ponderation" class="form-label">No</label>
    <input required name="ponderation" id="ponderation" type="text" placeholder="420-4P6-HU" class="form-control">
    @error('ponderation')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

<button type="submit" class="btn btn-primary">{{$texteBoutton}}</button>

resources/views/CritereEvaluation/index.blade.php
<x-app-layout>
    <div class="flex">
        <div class="">
            <div class="">
                <div class="">
                    <h1 class="">Ceci est la liste de critere d'evaluation</h1>
                </div>
                @auth
                    <div class="">
                        <a href="{{route('CritereEvaluation.create')}}" class="btn-primary">Ajouter</a>
                    </div>
                @endauth
            </div>
            <br>
            <table class="table table-striped">
                <tbody>
                @foreach($critereEvals as $critereEval)
                    <tr>
                        <th scope="row" >
                            <p>{{$critereEval->ennonce}} {{$critereEval->ponderation}}</p>
                        </th>
                        <td>
                            <a href="{{route('CritereEvaluation.show', $critereEval->id)}}">Voir</a>
                        </td>
                        <td>
                            <a href="{{route('CritereEvaluation.edit', $critereEval->id)}}">Modifier</a>
                        </td>
                        <td>
                            <a href="{{route('CritereEvaluation.destroy', $critereEval->id)}}">Effacer</a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>

resources/views/CritereEvaluation/modifier.blade.php
<x-app-layout>
    <h1>Modifier {{$critereevaluation->ennonce}}</h1>
    <form method="post" action="{{route('critereevaluation.update', ['critereevaluation'=>$critereevaluation->id])}}">
        @csrf
        @method('PUT')
        <x-formulaire-critere-evaluation texte-bouton="Modifier" :critereevaluation="$critereevaluation"></x-formulaire-critere-evaluation>
    </form>
</x-app-layout>

resources/views/CritereEvaluation/nouveau.blade.php
<x-app-layout>
    <h1>Nouvelle competence</h1>
    <form method="post" action="{{route('critereevaluation.create')}}">
        @csrf
        <x-formulaire-critere-evaluation texte-bouton="Nouveau"></x-formulaire-critere-evaluation>
    </form>
</x-app-layout>

resources/views/CritereEvaluation/show.blade.php
<?php