routes/web.php
<?php

use App\Http\Controllers\CompetenceController;
use App\Http\Controllers\CritereEvaluationController;
use App\Http\Controllers\CriterePerformanceController;
use App\Http\Controllers\ElementCompetenceController;
use App\Http\Controllers\PlanCadreController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProgrammeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::resource('competence', CompetenceController::class, [
    'parameters' => ['Competence' => 'competence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereevaluation', CritereEvaluationController::class, [
    'parameters' => ['CritereEvaluation' => 'critereevaluation']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('critereperformance', CriterePerformanceController::class, [
    'parameters' => ['CriterePerformance' => 'critereperformance']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('elementcompetence', ElementCompetenceController::class, [
    'parameters' => ['ElementCompetence' => 'elementcompetence']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('plancadre', PlanCadreController::class, [
    'parameters' => ['PlanCadre' => 'plancadre']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);

Route::resource('profil', ProfileController::class);

Route::resource('programme', ProgrammeController::class, [
    'parameters' => ['Programme' => 'programme']
])->only(['index', 'create', 'store', 'edit', 'update', 'destroy', 'show']);


Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/ElementCompetence.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ElementCompetence extends Model
{
    use HasFactory;

    protected $table = 'element_competences';

    public function competence(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Competence::class);
    }

    public function critereperformance(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(CriterePerformance::class, 'element_id');
    }

    protected $fillable = [
        'no',
        'texte',
        'contenu_local'
    ];
}

app/Http/Controllers/ElementCompetenceController.php
<?php

namespace App\Http\Controllers;

use App\Models\CriterePerformance;
use App\Models\ElementCompetence;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use JavaScript;

class ElementCompetenceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('elementcompetence.index', ['elementcompetence' => ElementCompetence::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        JavaScript::put([
            'critereperformances' => CriterePerformance::all()
        ]);

        return view('elementcompetence.nouveau');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $this->validateElement($request);
        $element = ElementCompetence::create([
            'no' => $request->no,
            'texte' => $request->texte,
            'contenu_local' => $request->contenu_local
        ]);

        if(isset($request->critereperformance)){
            $element->critereperformance()->attach(ElementCompetence::find($request->critereperformance));
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(ElementCompetence $elementCompetence)
    {
        return view ('elementcompetence.show', ['elementcompetence' => $elementCompetence]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        return view('elementcompetence.modifier', ['elementcompetence' => ElementCompetence::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, ElementCompetence $elementCompetence)
    {
        $this->validateElement($request);
        $element = ElementCompetence::where('id', $elementCompetence->id)->update([
            'no' => $request->no,
            'texte' => $request->texte,
            'contenu_local' => $request->contenu_local
        ]);

        if(isset($request->critereperformance)){
            $element->critereperformance()->attach(ElementCompetence::find($request->critereperformance));
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        Gate::authorize('isAdmin');
        $element = ElementCompetence::where('id' , $id)->delete();
    }

    public function validateElement(Request $request)
    {
        return $request->validate([
            'no' => 'required|string|max:255',
            'texte' => 'required|string|max:255',
            'contenu_local' => 'required|string'
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/formulaireElementCompetence.php
<?php

namespace App\View\Components;

use Illuminate\Database\Eloquent\Collection;
use App\Models\CriterePerformance;
use App\Models\ElementCompetence;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class formulaireElementCompetence extends Component
{
    public Collection $criterePerformance;
    public string $textBoutton;

    /**
     * Create a new component instance.
     */
    public function __construct(public string $texteBoutton = "Enregistrer", public ?ElementCompetence $elementcompetence = null)
    {
        $this->textBoutton = $this->texteBoutton;
        $this->criterePerformance = CriterePerformance::all();
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('elementcompetence.formulaire');
    }
}

resources/views/ElementCompetence/formulaire.blade.php
{{-- No --}}
<div class="my-3">
    <label for="no" class="form-label">Titre</label>
    <input required name="no" id="no" class="form-control">
    @error('no')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Texte --}}
<div class="my-3">
    <label for="texte" class="form-label">Titre</label>
    <input required name="texte" id="texte" class="form-control">
    @error('texte')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror
</div>

{{-- Critere Performance --}}
<div class="my-3">
    <div class="flex">
        <label for="critereperformance_plus" class="form-label">Critere de performance</label>
        <button id="critereperformance_plus" class="btn btn-secondary rounded-circle btn-sm" type="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
        </button>
        <a href="{{route('critereperformance.create')}}" type="button" class="btn btn-secondary btn-sm">Nouvelle</a>
    </div>
    <?php  // donner une id unique a toutes les composantes pour pas creer de trouble au submit
    $compte = 1; ?>
    <div id="critereperformance_select">{{--}}
        @if(isset($elementcompetence))
        @foreach($elementcompetence?->critereperformance as $critere)
            <select id="critereperformance{{$compte}}" name="critereperformance" class="form-select">
                <option value="">---</option>
                @foreach($competence as $competences)
                    @if($competences->id == $comp->id)
                        <option value="{{$competences->id}}" selected>{{$competences->titre}} - {{$competences->code}}</option>
                    @else
                        <option value="{{$competences->id}}">{{$competences->titre}} - {{$competences->code}}</option>
                    @endif
                @endforeach
            </select>
            <?php $compte += 1 ?>
        @endforeach
        @endif{{--}}
    </div>

    @error('competence')
    <div class="alert alert-danger">{{ $message }}</div>
    @enderror

</div>

<button type="submit" class="btn btn-primary">{{$textBoutton}}</button>

resources/views/ElementCompetence/index.blade.php
<x-app-layout>

</x-app-layout>

resources/views/ElementCompetence/modifier.blade.php
@include ('footer')
<x-app-layout>
    <h1>Modifier {{$elementcompetence->no}}</h1>
    <form method="post" action="{{route('elementcompetence.update', ['elementcompetence' => $elementcompetence->id])}}">
        @csrf
        @method('PUT')
        <x-formulaire-element-competence texte-bouton="Modifier" :elementcompetence="$elementcompetence"></x-formulaire-element-competence>
    </form>
</x-app-layout>

resources/views/ElementCompetence/nouveau.blade.php
@include ('footer')
<x-app-layout>
    <h1>Nouveau element de competence</h1>
    <form method="POST" action="{{route('elementcompetence.store')}}">
        @csrf
        <x-formulaire-element-competence texte-bouton="Nouveau"></x-formulaire-element-competence>
    </form>
</x-app-layout>